### ISSUE TITLE
Bug：未正常显示颜色

### ISSUE THREAD

**Issue by shigma** [koishijs/koi#24]
- 期望行为：在能够显示颜色的环境正常显示颜色，在不能显示颜色的环境不显示
- 实际行为：在能够显示颜色的环境有颜色丢失（可以接受），在不能显示颜色的环境打印了对应的控制字符

![image](https://user-images.githubusercontent.com/33423008/167474458-c65ddb5f-05da-4000-8467-51ab10faeed8.png)

![image](https://user-images.githubusercontent.com/33423008/167474679-8a91d195-dc50-470f-bd47-51489d29caaf.png)

**Comment by shigma** [comment]
<img width="570" alt="image" src="https://user-images.githubusercontent.com/33423008/167475979-000e8ff3-c5a1-4174-8722-4117905f2db5.png">

MacOS 效果图见上。我觉得显示不出颜色也可以理解。可以当成两个独立的问题分开处理。

**Comment by ilharp** [comment]
问题 1 为包 [nested-logrus-formatter](https://github.com/antonfisher/nested-logrus-formatter) 所致。发现该包提供了是否启用颜色的选项，推测该包不会自动判断当前终端环境的颜色支持情况。

需手动作出处理。需寻找 Go 世界是否有类 [supports-color](https://github.com/chalk/supports-color) 包的包。在成功解析后，需覆盖设置如下环境变量：

- `FORCE_COLOR`

- `TERM`

- `COLORTERM`

- `TERM_PROGRAM`（为 `koi`）

---

问题 2 则较为奇怪，[supports-color](https://github.com/chalk/supports-color) 包认为 Windows 10 的新版本 `conhost` 已经有了输入颜色的能力，故输出颜色。可能需要进一步调研。

**Comment by ilharp** [comment]
问题 2 的一种可能的产生原因是：

1. 包 [logrus](https://github.com/sirupsen/logrus) 以为 Windows 的 `conhost` 无输出颜色的能力（根据 [supports-color](https://github.com/chalk/supports-color) 包所述，该能力是在近期的 Windows 10 版本中才添加的）

2. 包 [logrus](https://github.com/sirupsen/logrus) 将该判断传递给了包 [nested-logrus-formatter](https://github.com/antonfisher/nested-logrus-formatter)，该包将 `Koishi` 尝试输出的任何内容直接用字符串输出。

3. 包 [supports-color](https://github.com/chalk/supports-color) 检测到这是 Windows 的新版本，尝试输出颜色。

最终输出了纯字符串。

**Comment by shigma** [comment]
一种方案：对 Koishi 进程的输出原样输出；对守护进程的输出模拟成 Koishi Logger 的风格。

**Comment by ilharp** [comment]
经调研，包 [logrus](https://github.com/sirupsen/logrus) 在该问题上争执了非常久。

- https://github.com/sirupsen/logrus/issues/306

- https://github.com/sirupsen/logrus/issues/379

- https://github.com/sirupsen/logrus/issues/763

- https://github.com/sirupsen/logrus/pull/822

- https://github.com/sirupsen/logrus/issues/824

- https://github.com/sirupsen/logrus/pull/957

- https://github.com/sirupsen/logrus/issues/965

认为该包有点拉跨。之前选择该包是因为 Docker 使用了该包。考虑更换解决方案。

---

> 一种方案：对 Koishi 进程的输出原样输出；对守护进程的输出模拟成 Koishi Logger 的风格。

上述方案听起来不错。准备使用该方案造新包，解决上述问题。

---

配置添加时间戳需要如何操作？

**Comment by shigma** [comment]
> 配置添加时间戳需要如何操作？

不用操作，我来改 boilerplate。

**Comment by ilharp** [comment]
> > 配置添加时间戳需要如何操作？
> 
> 不用操作，我来改 boilerplate。

好（

**Comment by shigma** [comment]
我那已经改过了，没动 boilerplate，直接把 cli 的 `logger.showTime` 默认值改 true 了。

**Comment by ilharp** [comment]
经调研，Windows 无法使用 PTY 方案，且由于该方案存在诸多缺陷，改用环境变量方案。
