### ISSUE TITLE
Bug：Windows 启动时会出现 chcp 报错（并且中文不可读）

### ISSUE THREAD

**Issue by shigma** [koishijs/koi#25]
![image](https://user-images.githubusercontent.com/33423008/167476570-86bd65ce-6356-4f63-925b-8f4ee9446dbf.png)

**Comment by shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/167480466-34f2a47d-fdb5-4dae-88b7-e5dcf56a21fe.png)

通过对比确认是 @koishijs/plugin-status 的问题。怀疑是用了 systeminformation 这个库导致的。下个版本打算把它扬了。

**Comment by ilharp** [comment]
尚不清楚该报错为何出现。根据提示应该是 Koishi 打印的日志。

可以检查：

1. Koishi 内部有调用 `chcp` 吗？

2. 在非 Koi 环境下是否会出现此问题？

**Comment by ilharp** [comment]
好，支持（

**Comment by shigma** [comment]
sysinfo 这个库会调用系统指令查看内存占用。感觉是这方面的原因。

https://github.com/koishijs/koishi/blob/master/plugins/frontend/status/src/profile.ts#L3

https://github.com/sebhildebrandt/systeminformation/blob/69987c5c60ae35ca90e77ff106e1238e26229129/lib/memory.js#L262-L287
